import { action } from 'typesafe-actions';
import { formsTypes } from './types';

export const loadAllFormsRequest = () => action(formsTypes.LOAD_ALL_FORMS_REQUEST);
export const loadAllFormsResponse = response => action(formsTypes.LOAD_ALL_FORMS_RESPONSE, response);
export const loadForm = payload => action(formsTypes.LOAD_FORM, payload);
export const loadFormResponse = response => action(formsTypes.LOAD_FORM_RESPONSE, response);
export const handleCreationModal = () => action(formsTypes.HANDLE_CREATION_MODAL);
export const handleDeleteModal = () => action(formsTypes.HANDLE_DELETE_MODAL);
export const handleToggleSideBar = () => action(formsTypes.HANDLE_TOGGLE_SIDE_BAR);
export const deleteFormRequest = payload => action(formsTypes.DELETE_FORM_REQUEST, payload);
export const deleteFormResponse = response => action(formsTypes.DELETE_FORM_RESPONSE, response);
export const clearDeleteFormStatus = () => action(formsTypes.CLEAR_DELETE_FORM_STATUS);
export const setFormSettings = payload => action(formsTypes.SET_FORM_SETTINGS, payload);
export const clearFormSettings = () => action(formsTypes.CLEAR_FORM_SETTINGS);
export const saveFormSettings = payload => action(formsTypes.SAVE_FORM_SETTINGS, payload);
export const startNewForm = () => action(formsTypes.START_NEW_FORM);
export const saveForm = () => action(formsTypes.SAVE_FORM);
export const setSaveFormErrors = payload => action(formsTypes.SET_SAVE_FORM_ERRORS, payload);
export const saveFormResponse = payload => action(formsTypes.SAVE_FORM_RESPONSE, payload);
export const handleDeleteStepModal = payload => action(formsTypes.HANDLE_DELETE_STEP_MODAL, payload);
export const duplicateStep = payload => action(formsTypes.DUPLICATE_STEP, payload);
export const deleteStep = payload => action(formsTypes.DELETE_STEP, payload);
export const handleMoveStepModal = payload => action(formsTypes.HANDLE_MOVE_STEP_MODAL, payload);
export const moveStep = payload => action(formsTypes.MOVE_STEP, payload);
export const createNewStep = payload => action(formsTypes.CREATE_NEW_STEP, payload);
export const setStepTitle = payload => action(formsTypes.SET_STEP_TITLE, payload);
export const addNewQuestion = payload => action(formsTypes.ADD_NEW_QUESTION, payload);
export const duplicateQuestion = payload => action(formsTypes.DUPLICATE_QUESTION, payload);
export const deleteQuestion = payload => action(formsTypes.DELETE_QUESTION, payload);
export const handleMoveQuestionModal = payload => action(formsTypes.HANDLE_MOVE_QUESTION_MODAL, payload);
export const moveQuestion = payload => action(formsTypes.MOVE_QUESTION, payload);
export const editQuestionField = payload => action(formsTypes.EDIT_QUESTION_FIELD, payload);
export const editQuestion = payload => action(formsTypes.EDIT_QUESTION, payload);
export const handleAnswerTypeModal = payload => action(formsTypes.HANDLE_ANSWER_TYPE_MODAL, payload);
export const selectAnswerType = payload => action(formsTypes.SELECT_ANSWER_TYPE, payload);
export const editAnswerType = payload => action(formsTypes.EDIT_ANSWER_TYPE, payload);
export const addAnswerOption = payload => action(formsTypes.ADD_ANSWER_OPTION, payload);
export const deleteAnswerOption = payload => action(formsTypes.DELETE_ANSWER_OPTION, payload);
export const editAnswerOption = payload => action(formsTypes.EDIT_ANSWER_OPTION, payload);
export const editOption = payload => action(formsTypes.EDIT_OPTION, payload);
export const moveOption = payload => action(formsTypes.MOVE_OPTION, payload);
export const clearValidateErrors = () => action(formsTypes.CLEAR_VALIDATE_ERRORS);
export const clearSaveFormStatus = payload => action(formsTypes.CLEAR_SAVE_FORM_STATUS, payload);
export const handleShareMode = payload => action(formsTypes.HANDLE_SHARE_MODE, payload);
export const duplicateForm = payload => action(formsTypes.DUPLICATE_FORM, payload);
export const clearCloneWarning = () => action(formsTypes.CLEAR_CLONE_WARNING);
export const loadAvailableUsers = () => action(formsTypes.LOAD_AVAILABLE_USERS);
export const loadAvailableUsersResponse = response => action(formsTypes.LOAD_AVAILABLE_USERS_RESPONSE, response);
export const clearLoadUsersStatus = payload => action(formsTypes.CLEAR_LOAD_USERS_STATUS, payload);
